const users = [
  {
    "photo": "https://randomuser.me/api/portraits/med/men/1.jpg",
    "hired": false,
    "email": "mclaughlin.dudley@gmail.com",
    "spec": "Support",
    "func": "Director",
    "type": "Remote Work",
    "experience": 4,
    "rate": 91,
    "username": "Mclaughlin Dudley",
    "isOnline": true,
    "id": "56f1ad53fe2cbff0eec7676a"
  },
  {
    "photo": "https://randomuser.me/api/portraits/med/women/2.jpg",
    "hired": true,
    "email": "elena.garza@gmail.com",
    "spec": "Social Media Marketing",
    "func": "Director",
    "type": "Half Time",
    "experience": 7,
    "rate": 47,
    "username": "Elena Garza",
    "isOnline": true,
    "id": "56f1ad53ba1845ede8fe489c"
  },
  {
    "photo": "https://randomuser.me/api/portraits/med/men/3.jpg",
    "hired": true,
    "email": "anastasia.terry@gmail.com",
    "spec": "Support",
    "func": "Manager",
    "type": "Half Time",
    "experience": 10,
    "rate": 29,
    "username": "Anastasia Terry",
    "isOnline": false,
    "id": "56f1ad53bd83d90e3c76e70e"
  },
  {
    "photo": "https://randomuser.me/api/portraits/med/men/4.jpg",
    "hired": false,
    "email": "barron.peters@gmail.com",
    "spec": "Social Media Marketing",
    "func": "Programmer",
    "type": "Remote Work",
    "experience": 2,
    "rate": 48,
    "username": "Barron Peters",
    "isOnline": true,
    "id": "56f1ad538d9c770ced1c5c75"
  },
  {
    "photo": "https://randomuser.me/api/portraits/med/women/5.jpg",
    "hired": true,
    "email": "claudia.crawford@gmail.com",
    "spec": "Support",
    "func": "Director",
    "type": "Half Time",
    "experience": 8,
    "rate": 85,
    "username": "Claudia Crawford",
    "isOnline": false,
    "id": "56f1ad53d6e69c6b04369382"
  },
  {
    "photo": "https://randomuser.me/api/portraits/med/women/6.jpg",
    "hired": false,
    "email": "alberta.serrano@gmail.com",
    "spec": "Social Media Marketing",
    "func": "Programmer",
    "type": "Remote Work",
    "experience": 10,
    "rate": 16,
    "username": "Alberta Serrano",
    "isOnline": true,
    "id": "56f1ad53167626ae7e0583cb"
  },
  {
    "photo": "https://randomuser.me/api/portraits/med/men/7.jpg",
    "hired": true,
    "email": "hart.dominguez@gmail.com",
    "spec": "Plumber",
    "func": "Programmer",
    "type": "Half Time",
    "experience": 9,
    "rate": 86,
    "username": "Hart Dominguez",
    "isOnline": true,
    "id": "56f1ad53d735d21cd3a4a713"
  },
  {
    "photo": "https://randomuser.me/api/portraits/med/women/8.jpg",
    "hired": false,
    "email": "viola.moss@gmail.com",
    "spec": "Support",
    "func": "Manager",
    "type": "Full Time",
    "experience": 1,
    "rate": 56,
    "username": "Viola Moss",
    "isOnline": false,
    "id": "56f1ad53fa54eeee1b16bc5f"
  },
  {
    "photo": "https://randomuser.me/api/portraits/med/women/9.jpg",
    "hired": false,
    "email": "hickman.church@gmail.com",
    "spec": "Front End Developer",
    "func": "Director",
    "type": "Full Time",
    "experience": 2,
    "rate": 2,
    "username": "Hickman Church",
    "isOnline": true,
    "id": "56f1ad539d39dd9281dddb23"
  },
  {
    "photo": "https://randomuser.me/api/portraits/med/men/10.jpg",
    "hired": false,
    "email": "lowery.harrington@gmail.com",
    "spec": "Plumber",
    "func": "Director",
    "type": "Full Time",
    "experience": 8,
    "rate": 2,
    "username": "Lowery Harrington",
    "isOnline": false,
    "id": "56f1ad53298a825c627b4d9b"
  },
  {
    "photo": "https://randomuser.me/api/portraits/med/women/11.jpg",
    "hired": true,
    "email": "aurelia.wiggins@gmail.com",
    "spec": "Front End Developer",
    "func": "Director",
    "type": "Full Time",
    "experience": 5,
    "rate": 97,
    "username": "Aurelia Wiggins",
    "isOnline": false,
    "id": "56f1ad53dd32fe860e336e53"
  },
  {
    "photo": "https://randomuser.me/api/portraits/med/women/12.jpg",
    "hired": true,
    "email": "taylor.yang@gmail.com",
    "spec": "Plumber",
    "func": "Director",
    "type": "Remote Work",
    "experience": 10,
    "rate": 18,
    "username": "Taylor Yang",
    "isOnline": false,
    "id": "56f1ad5324f0d746436591bc"
  },
  {
    "photo": "https://randomuser.me/api/portraits/med/women/13.jpg",
    "hired": false,
    "email": "lana.bush@gmail.com",
    "spec": "Support",
    "func": "Manager",
    "type": "Full Time",
    "experience": 1,
    "rate": 72,
    "username": "Lana Bush",
    "isOnline": true,
    "id": "56f1ad537c743dac0dda89c1"
  }
];

export default users;